### ISSUE TITLE
Better definition of levels?

### ISSUE THREAD

**Issue by mistermocha** [tenpages/us-level#7]
In particular, what's the difference between "Stayed" and "Visited", also "Stopped" and "Passing Through"?

I'm assuming "Passing Through" might mean you just drove through the state, maybe not stopping for more than fuel and coffee, but "Stopped" may mean you stop to do something more than just travel related, like ate at a restaurant or took a detour to see something new?

Similarly, "visited" may mean "just here briefly", but how brief? How much more of a "stop" becomes a "visit"? Following that, how long of a "visit" is a "stay"?

**Comment by heyakyra** [comment]
"stopped" is a stand in for having a layover: https://github.com/tenpages/us-level/issues/1#issuecomment-1283192280 not sure if stopping for gas/food counts, but it might? 

Not sure the difference between stayed and visited though

**Comment by brianleewow** [comment]
my take:
stayed - stayed overnight / slept
visited - a few hours or more / day trip, not just passing through
stopped - stopped for gas or food / flight layover. a functional stop rather than a visit.
passed - drove through without stopping

**Comment by bobpaul** [comment]
I still put "passed through" for places where I stopped for gas or food. Most US states are big enough that it's hard to pass through without stopping for gas, bathroom, or a non-descript meal (fast food, major chain, etc). But if it was a unique or memorable experience, then I'd rate it a stop or maybe even a visit.

Some overnights I didn't count as "stayed". I've slept in my car rest stops on the toil ways. That's a stop, not a stay, IMHO. And I've slept in airports, same deal.

Honestly I kinda like that the application doesn't define these things. It leaves it up to you and your friends to come up with your own definitions and that leads to discussions and stories about the trips you've all had.

**Comment by tenpages** [comment]
I don't have a specific standard. I'd rather let users decide. But as you can see there is an increase in points from passed, stopped, to visited or stayed, with an indication that the higher the points, the more "involvement" you have for this place.

The repo my code based upon set "lived" for "lived for more than a year", "stayed" for "stayed more than a month", and "visited" for "visited as a touring or business destination". "Stopped" would be for a layover or "eat/drink then continue the trip" situation, while "passed" means "traveled through without stopping".

Personally, I would suggest users deal with it with their own standard - the situation might be different from case to case. Imagine someone staying somewhere not for long but for daily life, not entertainment or business. I would say it is more of "lived" instead of "stayed" to me. But anyway - hope this would explain why I didn't set a standard and not going to.
